[package]
name = "ssg"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

[dependencies]
syntect.workspace = true
roc_highlight.workspace = true
roc_std.workspace = true
pulldown-cmark.workspace = true
