[package]
name = "roc_host"
version = "0.1.0"
edition = "2021"

[dependencies]
libc.workspace = true
roc_std.workspace = true
ssg.workspace = true
roc_env.workspace = true
roc_command.workspace = true
roc_io_error.workspace = true
roc_stdio.workspace = true
roc_file.workspace = true
