on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-examples-linux:
    runs-on: ubuntu-latest
    env:
      ROC_VERSION: nightly
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update apt-get
        run: sudo apt-get update

      - name: Install Build Essentials
        run: sudo apt install build-essential git

      - name: Install Rust and Cargo
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env

      - id: try_fetching_testing_release
        continue-on-error: true
        run: |
          curl -fOL https://github.com/roc-lang/roc/releases/download/nightly/roc_nightly-linux_x86_64-TESTING.tar.gz

      - name: There are no TESTING releases, checking regular releases instead
        if: steps.try_fetching_testing_release.outcome == 'failure'
        run: |
          curl -fOL https://github.com/roc-lang/roc/releases/download/nightly/roc_nightly-linux_x86_64-latest.tar.gz

      - name: rename nightly tar
        run: mv $(ls | grep "roc_nightly.*tar\.gz") roc_nightly.tar.gz

      - name: decompress the tar
        run: tar -xzf roc_nightly.tar.gz

      - run: rm roc_nightly.tar.gz

      - name: simplify nightly folder name
        run: mv roc_nightly* roc_nightly

      - name: Check ROC version
        run: ./roc_nightly/roc version

      - name: Run all tests
        run: ROC=./roc_nightly/roc ./ci/all_tests.sh

  test-examples-macos:
    runs-on: macos-latest
    env:
      ROC_VERSION: nightly
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Build Essentials
        run: brew install automake autoconf libtool

      - name: Install Rust and Cargo
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env

      - name: Export Homebrew paths for roc
        run: |
          brew install z3 zstd
          export LIBRARY_PATH="/opt/homebrew/lib:$LIBRARY_PATH"

      - name: Install ROC
        run: |
          # Install ROC
          curl -fOL https://github.com/roc-lang/roc/releases/download/${ROC_VERSION}/roc_nightly-macos_apple_silicon-latest.tar.gz
          mv $(ls | grep "roc_nightly.*tar\.gz") roc_nightly.tar.gz
          tar -xzf roc_nightly.tar.gz
          rm roc_nightly.tar.gz
          mv roc_nightly* roc_nightly

      - name: Check ROC version
        run: ./roc_nightly/roc version

      - name: Run all tests
        run: ROC=./roc_nightly/roc ./ci/all_tests.sh
