on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test-native:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - operating-system: ubuntu-20.04
            package-manager: apt
          - operating-system: ubuntu-22.04
            package-manager: apt
          - operating-system: macos-13
            package-manager: brew
          - operating-system: macos-14
            package-manager: brew
    steps:
      - uses: actions/checkout@v4

      - name: Install Roc
        uses: hasnep/setup-roc@v0.4.0
        with:
          roc-version: nightly
          testing: "true"

      - name: Check roc version
        run: roc version

      - name: Run all tests
        run: roc ./ci/all_tests.sh
